use-singularity: True
singularity-args: "-B /home/alfred/simkin_bioinformatics/miptools_analysis_variant_calling_troubleshooting/Mikalayi_dataset/IBC:/opt/project_resources
  -B /home/alfred/simkin_bioinformatics/miptools_analysis_variant_calling_troubleshooting/test-data/pf_species_resources:/opt/species_resources
  -B /home/alfred/simkin_bioinformatics/miptools_analysis_variant_calling_troubleshooting/Mikalayi_dataset:/opt/data
  -B /home/alfred/simkin_bioinformatics/miptools_analysis_variant_calling_troubleshooting/Mikalayi_dataset/jupyter_analysis:/opt/analysis
  -B /home/alfred/simkin_bioinformatics/miptools_analysis_variant_calling_troubleshooting/miptools_src:/opt/src
  --app jupyter"
printshellcmds: True
cores: 16
keep-going: True
rerun-incomplete: True
use-conda: True
latency-wait: 20
keep-incomplete: True
#restart-times: 3
