info_files: ['run_test_run_wrangled_20221102.txt.gz']
sample_sheets: ['sample_list.tsv']
sample_groups: [['JJJ', 'DR1,VAR4']]
species: pf
probe_sets_used: DR1
processorNumber: 12
minHaplotypeBarcodes: 1
minHaplotypeSamples: 1
minHaplotypeSampleFraction: 0.0001
barcode_threshold: 10
tick_label_size: 5
cbar_label_size: 5
dpi: 300
absent_color: beige
present_color: maroon
save: False
ytick_freq: null
xtick_freq: null
xtick_rotation: 90
high_barcode_threshold: 10000
low_coverage_action: Recapture
target_coverage_count: null
target_coverage_fraction: 0.95
target_coverage_key: targets_with_10_barcodes
barcode_coverage_threshold: 10
barcode_count_threshold: 100
assesment_key: targets_with_1_barcodes
good_coverage_quantile: 0.25
options: ["--pooled-continuous", "--min-alternate-fraction", "0.01", "--min-alternate-count", "2", "--haplotype-length", "3", "--min-alternate-total", "10", "--use-best-n-alleles", "70", "--genotype-qualities", "--gvcf", "--gvcf-dont-use-chunk", "true"]
align: True
verbose: True
fastq_dir: /opt/analysis/padded_fastqs
bam_dir: /opt/analysis/padded_bams
vcf_file: /opt/analysis/variants.vcf.gz
targets_file: /opt/project_resources/targets.tsv
errors_file: /opt/analysis/freebayes_errors.txt
warnings_file: /opt/analysis/freebayes_warnings.txt
fastq_padding: 20
geneid_to_genename: /opt/project_resources/geneid_to_genename.tsv
target_aa_annotation: /opt/project_resources/targets.tsv
aggregate_aminoacids: True
aggregate_nucleotides: True
target_nt_annotation: null
settings_file: null
annotate: True
decompose_options: []
annotated_vcf: False
aggregate_none: True
min_site_qual: 1
min_target_site_qual: 0
min_genotype_qual: 1
min_mean_alt_qual: 15
output_prefix: ""
mutation_count_file: /opt/analysis/alternate_AA_table.csv
mutation_coverage_file: /opt/analysis/coverage_AA_table.csv
min_count: 2
#these are filtering commands and they impact ___.csv files
min_coverage: 10
min_umi: 3

min_freq: 0
num_samples_wsaf: 2
min_wsaf: 0.5
num_samples_umi: 2
